# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    platform :ios, '14.1'
    pod 'domain', :path => '../domain'
    pod 'common', :path => '../common'
    pod 'data', :path => '../data'

  # Pods for CryptoApp

  target 'CryptoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoAppUITests' do
    # Pods for testing
  end

end
